//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negr
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GreenKazikEntities : DbContext
    {
        public GreenKazikEntities()
            : base("name=GreenKazikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Balances> Balances { get; set; }
        public virtual DbSet<Crits> Crits { get; set; }
        public virtual DbSet<Invent> Invent { get; set; }
        public virtual DbSet<InventItems> InventItems { get; set; }
        public virtual DbSet<Items> Items { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Phots> Phots { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
