//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Negr
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredients
    {
        public int IngredientID { get; set; }
        public Nullable<int> RecipeID { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
    
        public virtual Recipes Recipes { get; set; }
    }
}
